### ISSUE TITLE
关于数据集下载的问题

### ISSUE THREAD

**Issue by 1071189147** [sun11999/RDIAN#1]
您好，首先十分感谢您的贡献，我想提一个小小的建议，我在下载数据集时，发现阿里云盘转存特别慢，且偶尔转存失败，需要一个个去核对，阿里云盘太不方便了，请问是否有其他下载链接？

**Comment by sun11999** [comment]
您好，此数据集目前没有其他下载链接。
由于数据量较大，我们也在探索更好的分享方式，后续任何更新将会在实验室网站及时发布，感谢您的关注和建议！

**Comment by sun11999** [comment]
您好，新的分享链接（百度云、谷歌云）请见实验室网站 https://xzbai.buaa.edu.cn/datasets.html
