### ISSUE TITLE
IRDST的训练测试集划分可能存在数据泄露问题

### ISSUE THREAD

**Issue by XinyiYing** [sun11999/RDIAN#2]
IRDST在数据划分的时候，将同一序列的不同帧划分到训练和测试集中。由于同一序列内的目标和背景变化不大，因此会存在数据泄露，导致无法合理评估算法性能的情况。

因此，我们建议您能够重新对数据集进行划分，确保训练集和测试集隶属不同的序列。

希望您能够将上述意见纳入考虑修正现有的数据划分，并公开新的数据集划分“.txt”

建议您按real序列进行训练测试集划分，1-71（共65段数据，25.2G）为训练集，72-92（共20段数据，15G）。
建议您按simulate序列进行训练测试集划分，1-251（共250段数据，26.7G）为训练集，252-317（共66段数据，7.5G）。

**Comment by sun11999** [comment]
感谢您的提问和建议！

首先，IRDST当前的文件夹序号代表了对应数据采集场景的序号，同一场景下包含若干序列。同时，IRDST在制作中，通过抽帧和人工检查的方式进行了数据清洗，剔除了过于相似的单帧图像，一定程度上保证了序列内的数据多样性。
因此，针对单帧目标检测，可以使用当前的数据划分方式；但针对序列目标跟踪，当前的数据划分是不适用的。

最后，我们也会在未来继续更新数据集的使用方式，欢迎您提出问题和建议！
