### ISSUE TITLE
roc曲线

### ISSUE THREAD

**Issue by sxy2021** [sun11999/RDIAN#3]
你好，我想问下你们roc曲线是怎么画的，能不能介绍一下

**Comment by sun11999** [comment]
您好，文章中使用了两种roc曲线（目标级与像素级），主要差异在于检测率DR的计算，文章V. A中有介绍：

目标级：DR_target = 正确检测出的目标数目/所有目标数目
像素级：DR_pixel = 正确检测出的目标像素数目/所有目标像素数目

在此基础上，在1~255的范围内取若干阈值，计算检测率与虚警率，由此得到roc曲线。
