### ISSUE TITLE
请教：修改batchsize,模型不能收敛

### ISSUE THREAD

**Issue by whitesnowyyy** [sun11999/RDIAN#4]
尊敬的作者，您好
      我实验的参数，basesize--1024,cropsize--1024,batchsize--8,optimizier--SGD，跑了400epoch,显卡：GF4090。
但是，一直得不到收敛，还请多多指教。
![2023-09-05](https://github.com/sun11999/RDIAN/assets/120913574/d233d05c-3735-4e87-9f77-d3eced8be43b)

**Comment by sun11999** [comment]
您好，您的实验参数可以多试试不同batchsize和learning_rate，加快收敛。
但看起来validation过程中各metric始终为0是不对的，建议检查一下validation部分的数据是否正确进行了metric的计算。

**Comment by Web-AK** [comment]
@sun11999 @whitesnowyyy 您好 我想问一下数据集你们是怎么放的？train.py需不需要修改batch-size？
![image](https://github.com/sun11999/RDIAN/assets/60963694/1d3fb02a-c424-4c8c-8f59-6b7184c7522c)
![image](https://github.com/sun11999/RDIAN/assets/60963694/b413546d-8179-462a-a11e-8eb60269e217)

**Comment by Web-AK** [comment]
@sun11999 尊敬的作者，您好！
      在使用simulation数据集进行训练时，我也遇到了类似的问题：
      参数设置：basesize--512,cropsize--480,batchsize--24 learning_rate--0.005  显卡3090
![image](https://github.com/sun11999/RDIAN/assets/60963694/bb7107ee-f8d6-4b31-aea9-351d556bab02)
@whitesnowyyy 请问这个问题，您解决没有。

**Comment by sun11999** [comment]
您好！




测试指标均为0，应该是不合理的，会导致训练中无法存储更优参数，建议可以再做一下检查。




祝好，

孙衡







-----原始邮件-----
发件人:Web-AK ***@***.***>
发送时间:2023-10-26 22:56:26 (星期四)
收件人: sun11999/RDIAN ***@***.***>
抄送: "Heng Sun" ***@***.***>, Mention ***@***.***>
主题: Re: [sun11999/RDIAN] 请教：修改batchsize,模型不能收敛 (Issue #4)






@sun11999 尊敬的作者，您好！
在使用simulation数据集进行训练时，我也遇到了类似的问题：
参数设置：basesize--512,cropsize--480,batchsize--24 learning_rate--0.005 显卡3090

@whitesnowyyy 请问这个问题，您解决没有。

**Comment by Web-AK** [comment]
嗯嗯 我已收到

**Comment by SeaHifly** [comment]
朋友，你运行成功了没有，可以不可以帮忙测下模型的计算量与参数量，我这边用thop库算的参数量约有0.22M，与论文宣称的0.131M不符，想找个人对下答案

**Comment by Web-AK** [comment]
嗯嗯 我已收到

**Comment by Web-AK** [comment]
嗯嗯 我已收到
