### ISSUE TITLE
关于数据集的问题

### ISSUE THREAD

**Issue by Kroery** [sun11999/RDIAN#5]
您好，您在文中提到，real dataset包含来自85个场景的1760个序列组成的40650帧图像，simulation dataset包含来自317个场景的4170个序列组成的102077帧图像。其中的1760个序列和4170个序列指的是什么？我们下载的数据集中只看到了real dataset有85段，simulation dataset有317段。

**Comment by sun11999** [comment]
您好，IRDST当前的文件夹序号代表了对应数据采集场景的序号，同一场景下包含若干序列即不同视频。

**Comment by Kroery** [comment]
您好，我们想做多帧检测跟踪的任务，因此想要将这1760和4170个序列提取出来，请问我们应该怎么判断一个文件夹中有多少个序列？

**Comment by sun11999** [comment]
您好，目前的数据集没有保留与原始视频的对应关系，建议可以在同一文件夹下自行选择帧数抽取。
