### ISSUE TITLE
ROC Curve

### ISSUE THREAD

**Issue by karacanil** [sun11999/RDIAN#6]
Hello @sun11999 , 
The code regarding the calculation and plotting of the ROC Curve seems incomplete. What's the actual code like that is responsible for the ROC Curve operations, 
Thanks.

**Comment by sun11999** [comment]
The ROC curves in the paper are plotted using Matlab by computing false alarm (FA) and detection ratio (DR) under different thresholds. You can compute the metrics by the code and plot the curve by any tools.
