### ISSUE TITLE
数据集不能下载

### ISSUE THREAD

**Issue by RuiminHuang** [sun11999/RDIAN#8]
你好，点进链接下载数据集时，显示：

Forbidden
You don't have permission to access this resource.

**Comment by sun11999** [comment]
您好，该网站已维护完毕，可以通过Datasets部分的链接进行下载。

您也可以直接通过下方链接进行数据集下载
[Baidu Cloud 1](https://pan.baidu.com/s/1a_f7YEZjBxNaKKtvmsoUTw?pwd=9wu6)
[Baidu Cloud 2](https://pan.baidu.com/s/1KRwggMRrknb_Mh2zP7EuJg?pwd=ana1)
[Google Drive 1](https://drive.google.com/drive/folders/1bCZmLuyBDQQhRANXNVW6YvM2ftcQi5oO?usp=sharing)
[Google Drive 2](https://drive.google.com/drive/folders/1Ii9NvRvCDWaz_q2tW5XGcBfLxUzaBD3d?usp=sharing)

**Comment by YangBo0411** [comment]
你好，百度云和谷歌网盘都进不去。

**Comment by sun11999** [comment]
您好，




感谢您的关注，该数据集的各个链接随实验室网站一同维护中，预计下周会重新开放。




祝好，

孙衡










-----原始邮件-----
发件人:"Yang Bo" ***@***.***>
发送时间:2024-10-29 15:17:34 (星期二)
收件人: sun11999/RDIAN ***@***.***>
抄送: "Heng Sun" ***@***.***>, Comment ***@***.***>
主题: Re: [sun11999/RDIAN] 数据集不能下载 (Issue #8)






你好，百度云和谷歌网盘都进不去。
